version: '3.8'

services:
  spotify-slsk:
    build: .
    env:
      - SPOTIPY_CLIENT_ID=your-spotify-client-id
      - SPOTIPY_CLIENT_SECRET=your-spotify-client-secret
      - SPOTIPY_PLAYLIST_URLS="" #Comma separated list of Spotify playlist URLs
      - SLDL_USER=your-slsk-username
      - SLDL_PASS=your-slsk-password
    volumes:
      - ./data:/app/data
    restart: unless-stopped
