name: Build, Tag, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine the release type from labels
        id: release-label
        uses: actions-ecosystem/action-release-label@v1
        if: ${{ github.event.pull_request.merged == true }}

      - name: Get the latest tag
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        if: ${{ steps.release-label.outputs.level != null }}

      - name: Bump the version
        id: bump-semver
        uses: actions-ecosystem/action-bump-semver@v1
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/guilhermewolf/spotify-slsk/custom-actions-runner:latest
            ghcr.io/guilhermewolf/spotify-slsk/custom-actions-runner:${{ steps.bump-semver.outputs.new_version }}
        if: ${{ github.event_name == 'push' || steps.release-label.outputs.level != null }}

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io

      - name: Create GitHub Release
        if: ${{ steps.release-label.outputs.level != null }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          name: Release ${{ steps.bump-semver.outputs.new_version }}
          body: |
            ## What's Changed
            - PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}
          draft: false
          prerelease: false
